DIR_NONE = 0
DIR_LEFT = 1
DIR_RIGHT = 2
DIR_UP = 3
DIR_DOWN = 4

TILE_SIZE = 16

PLAYER_COLISION_WIDTH = TILE_SIZE - 4
PLAYER_COLISION_HEIGHT = TILE_SIZE - 4
PLAYER_COLISION_OFFSET_X = 2
PLAYER_COLISION_OFFSET_Y = 2

ANIMATION_SPEED_IDLE = 0.3
ANIMATION_SPEED_WALK = 0.1
ANIMATION_SPEED_ATTACK = 0.1
